package com.neobe.testeregulacao;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Beneficiario implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.Long id;
	@org.kie.api.definition.type.Label(value = "idade")
	private int idade;
	@org.kie.api.definition.type.Label(value = "nome")
	private java.lang.String nome;
	@org.kie.api.definition.type.Label(value = "negado")
	private java.lang.Boolean negado;

	public Beneficiario() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public int getIdade() {
		return this.idade;
	}

	public void setIdade(int idade) {
		this.idade = idade;
	}

	public java.lang.String getNome() {
		return this.nome;
	}

	public void setNome(java.lang.String nome) {
		this.nome = nome;
	}

	public java.lang.Boolean getNegado() {
		return this.negado;
	}

	public void setNegado(java.lang.Boolean negado) {
		this.negado = negado;
	}

	public Beneficiario(java.lang.Long id, int idade, java.lang.String nome,
			java.lang.Boolean negado) {
		this.id = id;
		this.idade = idade;
		this.nome = nome;
		this.negado = negado;
	}

}