package com.neobe.testeregulacao;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GuiaSolicitacao implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("id")
	private java.lang.Long id;
	@org.kie.api.definition.type.Label("dataSolicitacao")
	private java.time.LocalDate dataSolicitacao;

	@org.kie.api.definition.type.Label("beneficiario")
	private com.neobe.testeregulacao.Beneficiario beneficiario;

	@org.kie.api.definition.type.Label(value = "Negativas")
	private java.util.List<com.neobe.testeregulacao.Negativa> negativas;

	public GuiaSolicitacao() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.time.LocalDate getDataSolicitacao() {
		return this.dataSolicitacao;
	}

	public void setDataSolicitacao(java.time.LocalDate dataSolicitacao) {
		this.dataSolicitacao = dataSolicitacao;
	}

	public com.neobe.testeregulacao.Beneficiario getBeneficiario() {
		return this.beneficiario;
	}

	public void setBeneficiario(
			com.neobe.testeregulacao.Beneficiario beneficiario) {
		this.beneficiario = beneficiario;
	}

	public java.util.List<com.neobe.testeregulacao.Negativa> getNegativas() {
		return this.negativas;
	}

	public void setNegativas(
			java.util.List<com.neobe.testeregulacao.Negativa> negativas) {
		this.negativas = negativas;
	}

	public GuiaSolicitacao(java.lang.Long id,
			java.time.LocalDate dataSolicitacao,
			com.neobe.testeregulacao.Beneficiario beneficiario,
			java.util.List<com.neobe.testeregulacao.Negativa> negativas) {
		this.id = id;
		this.dataSolicitacao = dataSolicitacao;
		this.beneficiario = beneficiario;
		this.negativas = negativas;
	}

}