package com.neobe.testeregulacao;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Negativa implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.Integer id;
	@org.kie.api.definition.type.Label(value = "codigo")
	private java.lang.String codigo;
	@org.kie.api.definition.type.Label(value = "descricao")
	private java.lang.String descricao;

	public Negativa() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(java.lang.String codigo) {
		this.codigo = codigo;
	}

	public java.lang.String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(java.lang.String descricao) {
		this.descricao = descricao;
	}

	public Negativa(java.lang.Integer id, java.lang.String codigo,
			java.lang.String descricao) {
		this.id = id;
		this.codigo = codigo;
		this.descricao = descricao;
	}

}